name: pymetric
channels:
  - defaults
  - conda-forge
dependencies:
  - gdal>=3.0
  - matplotlib
  - netCDF4>=1.3.1
  - numpy>=1.14.0
  - pandas>=1.0.0
  - pip
  - python=3.7
  - refet>=0.3.7
  - requests
  - scipy>=1.0.0
  - pip:
    - drigo>=0.2.0
    - requests-html>=0.10.0

